import Link from 'next/link';
import { categories } from '../lib/data';
import { siteConfig } from '../lib/config';
import { Icon } from './icons';

export function SiteFooter() {
  return <>
    <section className="newsletter-section"><div className="container newsletter-inner"><div><span className="eyebrow">পাঠকের চিঠি</span><h2>নতুন বইয়ের খবর<br /><em>সবার আগে</em> জানুন</h2></div><form className="newsletter-form" action="#"><input type="email" placeholder="আপনার ইমেইল ঠিকানা" aria-label="ইমেইল ঠিকানা" /><button className="btn btn-primary" type="submit">সাবস্ক্রাইব করুন <Icon name="arrow" size={16} /></button><p>সপ্তাহে একবার। কোনো স্প্যাম নয়, শুধু ভালো বই।</p></form><div className="newsletter-mark" aria-hidden="true">“</div></div></section>
    <footer className="site-footer"><div className="container footer-grid"><div className="footer-brand"><Link href="/" className="brand footer-logo"><span className="brand-symbol">ব</span><span className="brand-copy"><b>বইপোকা</b><em>পড়ার আনন্দে, জীবনের গল্পে</em></span></Link><p>বই শুধু পড়া হয় না—বই আমাদের একটু একটু করে বদলে দেয়। আপনার পরের প্রিয় বইটি খুঁজে নিতে পাশে আছে বইপোকা।</p><div className="social-links"><a href={siteConfig.whatsappHref} aria-label="WhatsApp"><Icon name="whatsapp" size={18} /></a><a href="#facebook" aria-label="Facebook">f</a><a href="#instagram" aria-label="Instagram"><Icon name="instagram" size={17} /></a></div></div><div className="footer-column"><h3>দ্রুত লিংক</h3><Link href="/#popular">জনপ্রিয় বই</Link><Link href="/#new">নতুন বই</Link><Link href="/#offers">আজকের অফার</Link><Link href="/category/novel">সব ক্যাটাগরি</Link></div><div className="footer-column"><h3>জনপ্রিয় ক্যাটাগরি</h3>{categories.slice(0, 5).map((category) => <Link key={category.slug} href={`/category/${category.slug}`}>{category.name}</Link>)}</div><div className="footer-column footer-contact"><h3>সাহায্য দরকার?</h3><p>সকাল ৯টা — রাত ১০টা<br />প্রতিদিন</p><a className="footer-phone" href={siteConfig.whatsappHref}><Icon name="whatsapp" size={17} /> {siteConfig.whatsapp}</a><a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a><Link href="/delivery">ডেলিভারি তথ্য <Icon name="arrow" size={13} /></Link></div></div><div className="container footer-bottom"><span>© ২০২৪ বইপোকা। সর্বস্বত্ব সংরক্ষিত।</span><div><Link href="/privacy">গোপনীয়তা</Link><Link href="/terms">শর্তাবলি</Link><span className="payment-pills"><i>COD</i><i>বিকাশ</i></span></div></div></footer><a className="whatsapp-float" href={siteConfig.whatsappHref} aria-label="WhatsApp-এ মেসেজ করুন"><Icon name="whatsapp" size={22} /><span>কোনো প্রশ্ন আছে?</span></a>
  </>;
}
