import Link from 'next/link';
import { BookCard } from './components/book-card';
import { BookCover } from './components/book-cover';
import { Icon } from './components/icons';
import { SectionHeading } from './components/section-heading';
import { books, categories, authors } from './lib/data';

export default function HomePage() {
  const featured = books.filter((book) => book.isFeatured).slice(0, 4);
  const newBooks = books.filter((book) => book.isNew).slice(0, 4);
  const kids = books.filter((book) => book.categorySlug === 'kids');
  const islamic = books.filter((book) => book.categorySlug === 'islamic');
  const academic = books.filter((book) => ['academic', 'history', 'career'].includes(book.categorySlug));
  return <>
    <section className="hero-section"><div className="container hero-grid"><div className="hero-copy"><div className="hero-kicker"><span className="kicker-line" /> বইপোকার নির্বাচিত সংগ্রহ</div><h1>আপনার পছন্দের বই,<br /><em>এক জায়গায়</em></h1><p>জ্ঞান, গল্প, কল্পনা ও অনুপ্রেরণার বই বেছে নিন আপনার পছন্দ অনুযায়ী। আপনার পরের প্রিয় বইটি হয়তো এখানেই অপেক্ষা করছে।</p><div className="hero-actions"><Link href="#popular" className="btn btn-primary">বই দেখুন <Icon name="arrow" size={17} /></Link><Link href="#categories" className="btn btn-ghost">ক্যাটাগরি দেখুন <Icon name="arrow" size={16} /></Link></div><div className="hero-proof"><div className="proof-avatars"><span>আ</span><span>ম</span><span>স</span><span>+</span></div><p><strong>অনেক পাঠকের</strong><br />ভালোবাসায় বইপোকা</p></div></div><div className="hero-art"><div className="hero-stamp">EST.<br /><b>2024</b></div><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="hero-book hero-book-back"><BookCover book={books[2]} size="hero" priority /></div><div className="hero-book hero-book-middle"><BookCover book={books[3]} size="hero" priority /></div><div className="hero-book hero-book-front"><BookCover book={books[0]} size="hero" priority /></div><span className="hero-spark spark-one">✦</span><span className="hero-spark spark-two">✦</span><div className="hero-note"><span>এই মাসের বাছাই</span><b>পড়ুন, ভাবুন,<br />বদলে যান</b><Icon name="arrow" size={17} /></div></div></div></section>

    <section className="category-section" id="categories"><div className="container"><SectionHeading eyebrow="আপনার মনের মতো" title="কী পড়তে চান আজ?" description="একটি ভালো বই দিয়ে শুরু হোক আপনার আজকের সময়।" href="/category/novel" hrefLabel="সব ক্যাটাগরি" /><div className="category-grid">{categories.slice(0, 8).map((category) => <Link key={category.slug} href={`/category/${category.slug}`} className={`category-card tone-${category.tone}`}><span className="category-mark">{category.mark}</span><span className="category-name">{category.name}</span><span className="category-short">{category.short}</span><Icon name="arrow" size={17} /></Link>)}</div></div></section>

    <section className="books-section" id="popular"><div className="container"><SectionHeading eyebrow="পাঠকের পছন্দ" title="জনপ্রিয় বই" description="যে বইগুলো পাঠকেরা বারবার তুলে নিচ্ছেন।" href="/category/novel" /><div className="book-grid">{featured.map((book) => <BookCard key={book.slug} book={book} />)}</div></div></section>

    <section className="editorial-banner" id="offers"><div className="container editorial-inner"><div className="editorial-copy"><span className="eyebrow">বইপোকার বিশেষ আয়োজন</span><h2>কিছু গল্প<br /><em>সঙ্গে করে</em> নিয়ে যান</h2><p>পছন্দের বইয়ে ১৫% পর্যন্ত সাশ্রয়। আজকের বাছাই করা সংগ্রহ শেষ হওয়ার আগেই দেখে নিন।</p><Link href="/category/novel" className="btn btn-light">আজকের অফার দেখুন <Icon name="arrow" size={16} /></Link></div><div className="offer-books"><div className="offer-circle">—<br /><strong>১৫%</strong><br />পর্যন্ত</div><div className="offer-cover offer-cover-one"><BookCover book={books[4]} size="mini" /></div><div className="offer-cover offer-cover-two"><BookCover book={books[8]} size="mini" /></div><div className="offer-cover offer-cover-three"><BookCover book={books[1]} size="mini" /></div></div></div></section>

    <section className="books-section new-section" id="new"><div className="container"><SectionHeading eyebrow="সদ্য এসেছে" title="নতুন বই" description="আপনার বুকশেলফে জায়গা পাওয়ার অপেক্ষায়।" href="/category/novel" /><div className="book-grid">{newBooks.map((book) => <BookCard key={book.slug} book={book} />)}</div></div></section>

    <section className="split-section kids-section"><div className="container split-inner"><div className="split-visual kids-visual"><span className="visual-sun" /><div className="kids-note"><span>কৌতূহল থেকেই</span><b>বড় হয়<br />স্বপ্ন</b></div>{kids.map((book, index) => <div key={book.slug} className={`split-cover split-cover-${index}`}><BookCover book={book} size="mini" /></div>)}<span className="visual-doodle doodle-star">✦</span><span className="visual-doodle doodle-line">〰</span></div><div className="split-copy"><span className="eyebrow">ছোটদের বড় দুনিয়া</span><h2>শিশু-কিশোরদের<br /><em>বই</em></h2><p>গল্প, বিজ্ঞান, কল্পনা আর মজার সব প্রশ্নের উত্তর—ছোটদের জন্য বেছে নেওয়া বইয়ের আলাদা একটি তাক।</p><Link href="/category/kids" className="btn btn-dark">বইগুলো দেখুন <Icon name="arrow" size={16} /></Link></div></div></section>

    <section className="split-section islamic-section"><div className="container split-inner split-reverse"><div className="split-copy"><span className="eyebrow">জ্ঞান ও আত্মশুদ্ধি</span><h2>ইসলামিক<br /><em>বই</em></h2><p>বিশ্বাস, জীবন ও আত্মার পাঠকে আরও গভীর করতে মননশীল কিছু বই—শ্রদ্ধা ও যত্নের সঙ্গে বেছে নেওয়া।</p><Link href="/category/islamic" className="btn btn-emerald">ইসলামিক বই দেখুন <Icon name="arrow" size={16} /></Link></div><div className="split-visual islamic-visual"><div className="islamic-arch"><span>اقرأ</span></div>{islamic.map((book, index) => <div key={book.slug} className={`split-cover islamic-cover-${index}`}><BookCover book={book} size="mini" /></div>)}<span className="visual-doodle islamic-star">✦</span></div></div></section>

    <section className="academic-section"><div className="container academic-inner"><div><span className="eyebrow">শেখার পথ সহজ হোক</span><h2>শিক্ষা ও<br /><em>একাডেমিক</em></h2><p>পরীক্ষার প্রস্তুতি থেকে নিজের জ্ঞান বাড়ানো—শিক্ষার্থীদের জন্য গুছিয়ে রাখা দরকারি বই।</p><Link href="/category/academic" className="btn btn-navy">শিক্ষার বই দেখুন <Icon name="arrow" size={16} /></Link></div><div className="academic-stack">{academic.map((book, index) => <div key={book.slug} className={`academic-book academic-book-${index}`}><BookCover book={book} size="mini" /></div>)}<div className="academic-label"><Icon name="book" size={17} /> শেখার কোনো শেষ নেই</div></div></div></section>

    <section className="authors-section"><div className="container"><SectionHeading eyebrow="শব্দের কারিগররা" title="জনপ্রিয় লেখক" description="যাদের লেখা আমাদের একটু থামতে, ভাবতে শেখায়।" href="/author/humayun-ahmed" hrefLabel="সব লেখক" /><div className="authors-grid">{authors.map((author, index) => <Link href={`/author/${author.slug}`} className={`author-card author-${index}`} key={author.slug}><span className="author-initial">{author.name.slice(0, 1)}</span><span className="author-meta"><b>{author.name}</b><small>{author.note}</small><em>{author.books}</em></span><Icon name="arrow" size={16} /></Link>)}</div></div></section>

    <section className="trust-section"><div className="container trust-grid"><div className="trust-intro"><span className="eyebrow">নিশ্চিন্তে বেছে নিন</span><h2>বই কেনা হোক<br /><em>সহজ ও আনন্দের।</em></h2></div><div className="trust-item"><span className="trust-icon"><Icon name="truck" size={22} /></span><div><b>দ্রুত ডেলিভারি</b><p>ঢাকার ভেতরে ও বাইরে</p></div></div><div className="trust-item"><span className="trust-icon"><Icon name="shield" size={22} /></span><div><b>অথেন্টিক বই</b><p>নির্ভরযোগ্য প্রকাশনা থেকে</p></div></div><div className="trust-item"><span className="trust-icon"><Icon name="box" size={22} /></span><div><b>সহজ অর্ডার</b><p>ক্যাশ অন ডেলিভারি সুবিধা</p></div></div></div></section>
  </>;
}
