'use client';

import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { useStore } from '../components/store-provider';
import { Breadcrumbs } from '../components/breadcrumbs';
import { BookCover } from '../components/book-cover';
import { Icon } from '../components/icons';
import { formatPrice } from '../lib/data';
import { siteConfig } from '../lib/config';

export default function CheckoutPage() {
  const { cart, cartTotal, clearCart } = useStore();
  const [location, setLocation] = useState('dhaka');
  const [ordered, setOrdered] = useState(false);
  const delivery = location === 'dhaka' ? 60 : 120;
  const orderId = `ORD-${Math.floor(1000 + Math.random() * 9000)}`;
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setOrdered(true); clearCart(); };
  if (ordered) return <div className="checkout-page container"><div className="order-success"><span className="success-check"><Icon name="check" size={28} /></span><span className="eyebrow">ধন্যবাদ</span><h1>আপনার অর্ডারটি<br /><em>সফলভাবে গ্রহণ করা হয়েছে।</em></h1><p>আপনার অর্ডার নম্বর <strong>{orderId}</strong><br />আমরা খুব শিগগিরই আপনার সঙ্গে যোগাযোগ করব।</p><div className="success-note"><Icon name="phone" size={19} /> অর্ডার সংক্রান্ত যেকোনো প্রয়োজনে কল করুন <b>{siteConfig.whatsapp}</b></div><Link href="/" className="btn btn-primary">আরও বই দেখুন <Icon name="arrow" size={16} /></Link></div></div>;
  if (!cart.length) return <div className="checkout-page container"><div className="empty-cart checkout-empty"><span className="empty-cart-icon"><Icon name="cart" size={34} /></span><h2>অর্ডার করার মতো কোনো বই নেই</h2><p>আগে আপনার পছন্দের বইগুলো কার্টে যোগ করুন।</p><Link href="/" className="btn btn-primary">বই দেখতে যান <Icon name="arrow" size={16} /></Link></div></div>;
  return <div className="checkout-page container"><Breadcrumbs items={[{ label: 'কার্ট', href: '/cart' }, { label: 'অর্ডার সম্পন্ন করুন' }]} /><div className="checkout-heading"><span className="eyebrow">আর এক ধাপ</span><h1>অর্ডার সম্পন্ন করুন</h1><div className="checkout-steps"><span className="done"><i>✓</i> কার্ট</span><b /><span className="active"><i>২</i> তথ্য দিন</span><b /><span><i>৩</i> নিশ্চিত</span></div></div><div className="checkout-layout"><form className="checkout-form" onSubmit={submit}><section className="form-section"><div className="form-section-heading"><span>০১</span><div><h2>আপনার তথ্য</h2><p>ডেলিভারির জন্য তথ্যগুলো দিন</p></div></div><div className="form-grid"><label>আপনার নাম <input required name="name" placeholder="যেমন: তানভীর আহমেদ" /></label><label>মোবাইল নম্বর <input required name="phone" type="tel" placeholder="01XXXXXXXXX" pattern="01[0-9]{9}" /></label></div><label>সম্পূর্ণ ঠিকানা <textarea required name="address" rows={3} placeholder="বাড়ি/ফ্ল্যাট, রোড, এলাকা লিখুন" /></label><div className="location-options"><span>ডেলিভারি লোকেশন</span><label className={location === 'dhaka' ? 'selected' : ''}><input type="radio" name="location" value="dhaka" checked={location === 'dhaka'} onChange={() => setLocation('dhaka')} /> Inside Dhaka <small>৳৬০</small></label><label className={location === 'outside' ? 'selected' : ''}><input type="radio" name="location" value="outside" checked={location === 'outside'} onChange={() => setLocation('outside')} /> Outside Dhaka <small>৳১২০</small></label></div><label>অতিরিক্ত নোট <textarea name="notes" rows={2} placeholder="ডেলিভারি সংক্রান্ত কোনো কথা থাকলে লিখুন (ঐচ্ছিক)" /></label></section><section className="form-section payment-section"><div className="form-section-heading"><span>০২</span><div><h2>পেমেন্ট পদ্ধতি</h2><p>আপনার পছন্দের পেমেন্ট পদ্ধতি বেছে নিন</p></div></div><label className="payment-option selected"><input type="radio" checked readOnly /><span><b>ক্যাশ অন ডেলিভারি</b><small>পণ্য হাতে পাওয়ার পর মূল্য পরিশোধ করুন</small></span><Icon name="box" size={22} /></label></section><button type="submit" className="btn btn-primary btn-large confirm-button">অর্ডার নিশ্চিত করুন <Icon name="arrow" size={17} /></button></form><aside className="checkout-summary"><h2>আপনার অর্ডার</h2>{cart.map(({ book, quantity }) => <div className="checkout-product" key={book.slug}><BookCover book={book} size="mini" /><div><b>{book.title}</b><span>{quantity} × {formatPrice(book.price)}</span></div><strong>{formatPrice(book.price * quantity)}</strong></div>)}<div className="summary-divider" /><div className="summary-row"><span>বইয়ের মূল্য</span><strong>{formatPrice(cartTotal)}</strong></div><div className="summary-row"><span>ডেলিভারি চার্জ</span><strong>{formatPrice(delivery)}</strong></div><div className="summary-total"><span>সর্বমোট</span><strong>{formatPrice(cartTotal + delivery)}</strong></div><p className="secure-note"><Icon name="shield" size={15} /> আপনার তথ্য নিরাপদে রাখা হবে</p></aside></div></div>;
}
